"""Exhaustively validate routes generated by unified.py.

The validator fixes the start point and checks every permutation of the
destination IDs. By default it uses the closed-tour distance used by
``unified.py:get_optimized_destination_order``. Use ``--mode open`` to validate
the displayed itinerary without a return leg to the start point.

Examples
--------
Validate the current route from a running Flask application:

    python validation/Validation.py --url http://127.0.0.1:5000

Validate an explicitly supplied route:

    python validation/Validation.py --start-id 1 --route 2,3,4,5,6,7

Validate both the closed TSP objective and the open displayed itinerary:

    python validation/Validation.py --url http://127.0.0.1:5000 --mode both
"""

from __future__ import annotations

import argparse
import csv
import itertools
import json
import math
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple
from urllib.error import HTTPError, URLError
from urllib.request import urlopen


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CSV_PATH = PROJECT_ROOT / "spots.csv"
DEFAULT_APP_URL = "http://127.0.0.1:5000"
MAX_EXHAUSTIVE_DESTINATIONS = 9
DEFAULT_TOLERANCE = 1e-9

Coordinate = Tuple[float, float]
CoordinateMap = Dict[int, Coordinate]
NameMap = Dict[int, str]


def load_spots(csv_path: Path) -> Tuple[CoordinateMap, NameMap]:
    """Load spot coordinates and names from the same CSV used by unified.py."""
    coordinates: CoordinateMap = {}
    names: NameMap = {}

    with csv_path.open("r", encoding="utf-8-sig", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {csv_path}")

        normalized_fields = {
            field.strip().lower().replace(" ", "_"): field
            for field in reader.fieldnames
        }
        required = {"spot_id", "location_x", "location_y"}
        missing = sorted(required - normalized_fields.keys())
        if missing:
            raise ValueError(
                f"CSV is missing required columns: {', '.join(missing)}"
            )

        for row in reader:
            spot_id = int(row[normalized_fields["spot_id"]])
            coordinates[spot_id] = (
                float(row[normalized_fields["location_x"]]),
                float(row[normalized_fields["location_y"]]),
            )
            name_field = normalized_fields.get("spot_name")
            names[spot_id] = (
                str(row[name_field]).strip() if name_field else str(spot_id)
            )

    return coordinates, names


def euclidean_distance(point_a: Coordinate, point_b: Coordinate) -> float:
    """Use the same Euclidean coordinate distance as unified.py."""
    return math.hypot(point_a[0] - point_b[0], point_a[1] - point_b[1])


def route_distance(
    start_id: int,
    destination_ids: Sequence[int],
    coordinates: CoordinateMap,
    closed: bool,
) -> float:
    """Calculate start-to-destinations distance, optionally returning to start."""
    route_ids = [start_id, *destination_ids]
    distance = sum(
        euclidean_distance(coordinates[current_id], coordinates[next_id])
        for current_id, next_id in zip(route_ids, route_ids[1:])
    )

    if closed and destination_ids:
        distance += euclidean_distance(
            coordinates[destination_ids[-1]],
            coordinates[start_id],
        )

    return distance


def find_global_optimum(
    start_id: int,
    destination_ids: Sequence[int],
    coordinates: CoordinateMap,
    closed: bool,
    tolerance: float,
) -> Tuple[float, List[Tuple[int, ...]], int]:
    """Exhaustively search every destination ordering."""
    best_distance = math.inf
    best_routes: List[Tuple[int, ...]] = []
    checked_count = 0

    for candidate in itertools.permutations(destination_ids):
        checked_count += 1
        candidate_distance = route_distance(
            start_id,
            candidate,
            coordinates,
            closed,
        )

        if candidate_distance < best_distance - tolerance:
            best_distance = candidate_distance
            best_routes = [candidate]
        elif math.isclose(
            candidate_distance,
            best_distance,
            rel_tol=tolerance,
            abs_tol=tolerance,
        ):
            best_routes.append(candidate)

    return best_distance, best_routes, checked_count


def validate_ids(
    start_id: int,
    destination_ids: Sequence[int],
    coordinates: CoordinateMap,
) -> None:
    """Reject invalid or ambiguous routes before exhaustive validation."""
    if not destination_ids:
        raise ValueError("The route must contain at least one destination.")
    if len(destination_ids) > MAX_EXHAUSTIVE_DESTINATIONS:
        raise ValueError(
            "Exhaustive validation is limited to "
            f"{MAX_EXHAUSTIVE_DESTINATIONS} destinations; received "
            f"{len(destination_ids)}."
        )
    if start_id in destination_ids:
        raise ValueError("The start ID must not also appear as a destination.")
    if len(set(destination_ids)) != len(destination_ids):
        raise ValueError("Destination IDs must be unique.")

    missing_ids = [
        spot_id
        for spot_id in [start_id, *destination_ids]
        if spot_id not in coordinates
    ]
    if missing_ids:
        raise ValueError(
            "The following spot IDs were not found in the CSV: "
            + ", ".join(str(spot_id) for spot_id in missing_ids)
        )


def fetch_generated_route(app_url: str) -> Tuple[int, List[int]]:
    """Read the current generated route from Flask's /api/route-data endpoint."""
    endpoint = f"{app_url.rstrip('/')}/api/route-data"

    try:
        with urlopen(endpoint, timeout=10) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        details = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(
            f"Route endpoint returned HTTP {exc.code}: {details}"
        ) from exc
    except URLError as exc:
        raise RuntimeError(
            f"Could not connect to {endpoint}. Start the Flask application or "
            "supply --start-id and --route."
        ) from exc

    if payload.get("error"):
        raise RuntimeError(str(payload["error"]))

    current_location = payload.get("current_location") or {}
    route_spots = payload.get("route") or []
    if "spot_id" not in current_location or not route_spots:
        raise RuntimeError("The route endpoint did not return a complete route.")

    start_id = int(current_location["spot_id"])
    destination_ids = [int(spot["spot_id"]) for spot in route_spots]
    return start_id, destination_ids


def parse_route_ids(value: str) -> List[int]:
    """Parse comma-separated destination IDs."""
    route_ids = [
        int(item.strip())
        for item in value.split(",")
        if item.strip()
    ]
    if not route_ids:
        raise argparse.ArgumentTypeError(
            "Route must contain comma-separated destination IDs."
        )
    return route_ids


def format_route(
    start_id: int,
    destination_ids: Iterable[int],
    names: NameMap,
) -> str:
    """Format a route with IDs and readable spot names."""
    route_ids = [start_id, *destination_ids]
    return " -> ".join(
        f"{spot_id} ({names.get(spot_id, 'Unknown')})"
        for spot_id in route_ids
    )


def validate_mode(
    mode: str,
    start_id: int,
    destination_ids: Sequence[int],
    coordinates: CoordinateMap,
    names: NameMap,
    tolerance: float,
) -> bool:
    """Validate and print one distance objective."""
    closed = mode == "closed"
    generated_distance = route_distance(
        start_id,
        destination_ids,
        coordinates,
        closed,
    )
    best_distance, best_routes, checked_count = find_global_optimum(
        start_id,
        destination_ids,
        coordinates,
        closed,
        tolerance,
    )
    is_shortest = math.isclose(
        generated_distance,
        best_distance,
        rel_tol=tolerance,
        abs_tol=tolerance,
    )

    print(f"\n[{mode.upper()} ROUTE VALIDATION]")
    print(f"Permutations checked : {checked_count}")
    print(f"Generated distance   : {generated_distance:.12f}")
    print(f"Global best distance : {best_distance:.12f}")
    print(f"Distance difference  : {generated_distance - best_distance:.12f}")
    print(f"Result               : {'PASS - globally shortest' if is_shortest else 'FAIL - not globally shortest'}")

    if not is_shortest:
        print("One shortest route   :")
        print(f"  {format_route(start_id, best_routes[0], names)}")
    elif len(best_routes) > 1:
        print(f"Equivalent optima    : {len(best_routes)}")

    return is_shortest


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Verify whether a route generated by unified.py is globally "
            "shortest by checking every destination permutation."
        )
    )
    source_group = parser.add_mutually_exclusive_group()
    source_group.add_argument(
        "--url",
        nargs="?",
        const=DEFAULT_APP_URL,
        help=(
            "Read the current route from APP_URL/api/route-data. "
            f"Default APP_URL: {DEFAULT_APP_URL}"
        ),
    )
    source_group.add_argument(
        "--route",
        type=parse_route_ids,
        help="Comma-separated generated destination IDs.",
    )
    parser.add_argument(
        "--start-id",
        type=int,
        help="Start spot ID. Required when --route is used.",
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=DEFAULT_CSV_PATH,
        help=f"Path to spots CSV. Default: {DEFAULT_CSV_PATH}",
    )
    parser.add_argument(
        "--mode",
        choices=("closed", "open", "both"),
        default="closed",
        help=(
            "closed matches unified.py's TSP objective; open excludes the "
            "return leg; both reports both results. Default: closed"
        ),
    )
    parser.add_argument(
        "--tolerance",
        type=float,
        default=DEFAULT_TOLERANCE,
        help=f"Floating-point comparison tolerance. Default: {DEFAULT_TOLERANCE}",
    )
    return parser


def main() -> int:
    parser = build_argument_parser()
    args = parser.parse_args()

    if args.route is not None:
        if args.start_id is None:
            parser.error("--start-id is required when --route is used.")
        start_id = args.start_id
        destination_ids = args.route
        source = "command-line route"
    else:
        app_url = args.url or DEFAULT_APP_URL
        start_id, destination_ids = fetch_generated_route(app_url)
        source = f"{app_url.rstrip('/')}/api/route-data"

    coordinates, names = load_spots(args.csv.resolve())
    validate_ids(start_id, destination_ids, coordinates)

    print("Route Validation")
    print("================")
    print(f"Source               : {source}")
    print(f"Start ID             : {start_id}")
    print(f"Destination count    : {len(destination_ids)}")
    print("Generated route      :")
    print(f"  {format_route(start_id, destination_ids, names)}")

    modes = ("closed", "open") if args.mode == "both" else (args.mode,)
    results = [
        validate_mode(
            mode,
            start_id,
            destination_ids,
            coordinates,
            names,
            args.tolerance,
        )
        for mode in modes
    ]

    return 0 if all(results) else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"Validation error: {exc}", file=sys.stderr)
        raise SystemExit(2)
